// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJksjv_70ZPC0fAY5QChRyVTzik8PB0Wc',
    appId: '1:961082439262:web:1e2d3d97f484d6d6c666cf',
    messagingSenderId: '961082439262',
    projectId: 'db-smart-home',
    authDomain: 'db-smart-home.firebaseapp.com',
    databaseURL: 'https://db-smart-home-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'db-smart-home.firebasestorage.app',
    measurementId: 'G-H298LF60VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmnJE_h1lUiTC9CPijVnS44wyZfJM0K2Q',
    appId: '1:961082439262:android:322ee3a25a63a00fc666cf',
    messagingSenderId: '961082439262',
    projectId: 'db-smart-home',
    databaseURL: 'https://db-smart-home-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'db-smart-home.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzCsEYqx23cSBSKmeQn4tM1aWj2NfPx6U',
    appId: '1:961082439262:ios:63e57ed49c4de91dc666cf',
    messagingSenderId: '961082439262',
    projectId: 'db-smart-home',
    databaseURL: 'https://db-smart-home-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'db-smart-home.firebasestorage.app',
    iosBundleId: 'com.example.shome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzCsEYqx23cSBSKmeQn4tM1aWj2NfPx6U',
    appId: '1:961082439262:ios:63e57ed49c4de91dc666cf',
    messagingSenderId: '961082439262',
    projectId: 'db-smart-home',
    databaseURL: 'https://db-smart-home-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'db-smart-home.firebasestorage.app',
    iosBundleId: 'com.example.shome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtu_AymohykRTGaGzA93KxiXnfNfT1_GY',
    appId: '1:961082439262:web:e5901f6b3dde3b5dc666cf',
    messagingSenderId: '961082439262',
    projectId: 'db-smart-home',
    authDomain: 'db-smart-home.firebaseapp.com',
    databaseURL: 'https://db-smart-home-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'db-smart-home.firebasestorage.app',
    measurementId: 'G-ZW3R5FXKTH',
  );
}
